version: '3.9'

services:
  deliveryservice.api:
    image: ${DOCKER_REGISTRY-}deliveryserviceapi
    build:
      context: .
      dockerfile: DeliveryService/DeliveryService.API/Dockerfile

  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: OrderService/OrderService.API/Dockerfile

