version: '3.9'

services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: sa
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
        
  rabbitmq:
    image: rabbitmq:3.12.4-management
    environment:
      RABBITMQ_DEFAULT_USER: sa
      RABBITMQ_DEFAULT_PASS: sa
    ports:
      - "5672:5672"
      - "15672:15672"
  
  seq:
    image: datalust/seq:2023.3
    environment:
      - ACCEPT_EULA=Y
      - memory=1g
      - memory-swap=1g
    ports:
      - "5341:5341"
      - "5342:80"
  
  deliveryservice.api:
    image: ${DOCKER_REGISTRY-}deliveryserviceapi
    build:
      context: .
      dockerfile: DeliveryService/DeliveryService.API/Dockerfile

  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: OrderService/OrderService.API/Dockerfile

volumes:
  postgres-data: